// generated by template, do not modify manually

namespace Coplt.Arches;

public static partial class ArcheTypes
{
    public static TypeSet<T0> Of<T0>() => default;
    public static TypeSet<T0, T1> Of<T0, T1>() => default;
    public static TypeSet<T0, T1, T2> Of<T0, T1, T2>() => default;
    public static TypeSet<T0, T1, T2, T3> Of<T0, T1, T2, T3>() => default;
    public static TypeSet<T0, T1, T2, T3, T4> Of<T0, T1, T2, T3, T4>() => default;
    public static TypeSet<T0, T1, T2, T3, T4, T5> Of<T0, T1, T2, T3, T4, T5>() => default;
    public static TypeSet<T0, T1, T2, T3, T4, T5, T6> Of<T0, T1, T2, T3, T4, T5, T6>() => default;
    public static TypeSet<T0, T1, T2, T3, T4, T5, T6, T7> Of<T0, T1, T2, T3, T4, T5, T6, T7>() => default;
}
