// generated by template, do not modify manually

namespace Coplt.Arches.TypeSets;

public readonly partial record struct TypeSet<T0>
{

    public TypeSet<T0, T1> With<T1>() => default;

    public TypeSet<T0, T1, T2> With<T1, T2>() => default;

    public TypeSet<T0, T1, T2, T3> With<T1, T2, T3>() => default;

    public TypeSet<T0, T1, T2, T3, T4> With<T1, T2, T3, T4>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5> With<T1, T2, T3, T4, T5>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5, T6> With<T1, T2, T3, T4, T5, T6>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5, T6, T7> With<T1, T2, T3, T4, T5, T6, T7>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8> With<T1, T2, T3, T4, T5, T6, T7, T8>() => default;

}

public readonly partial record struct TypeSet<T0, T1>
{

    public TypeSet<T0, T1, T2> With<T2>() => default;

    public TypeSet<T0, T1, T2, T3> With<T2, T3>() => default;

    public TypeSet<T0, T1, T2, T3, T4> With<T2, T3, T4>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5> With<T2, T3, T4, T5>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5, T6> With<T2, T3, T4, T5, T6>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5, T6, T7> With<T2, T3, T4, T5, T6, T7>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8> With<T2, T3, T4, T5, T6, T7, T8>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9> With<T2, T3, T4, T5, T6, T7, T8, T9>() => default;

}

public readonly partial record struct TypeSet<T0, T1, T2>
{

    public TypeSet<T0, T1, T2, T3> With<T3>() => default;

    public TypeSet<T0, T1, T2, T3, T4> With<T3, T4>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5> With<T3, T4, T5>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5, T6> With<T3, T4, T5, T6>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5, T6, T7> With<T3, T4, T5, T6, T7>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8> With<T3, T4, T5, T6, T7, T8>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9> With<T3, T4, T5, T6, T7, T8, T9>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10> With<T3, T4, T5, T6, T7, T8, T9, T10>() => default;

}

public readonly partial record struct TypeSet<T0, T1, T2, T3>
{

    public TypeSet<T0, T1, T2, T3, T4> With<T4>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5> With<T4, T5>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5, T6> With<T4, T5, T6>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5, T6, T7> With<T4, T5, T6, T7>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8> With<T4, T5, T6, T7, T8>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9> With<T4, T5, T6, T7, T8, T9>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10> With<T4, T5, T6, T7, T8, T9, T10>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11> With<T4, T5, T6, T7, T8, T9, T10, T11>() => default;

}

public readonly partial record struct TypeSet<T0, T1, T2, T3, T4>
{

    public TypeSet<T0, T1, T2, T3, T4, T5> With<T5>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5, T6> With<T5, T6>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5, T6, T7> With<T5, T6, T7>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8> With<T5, T6, T7, T8>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9> With<T5, T6, T7, T8, T9>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10> With<T5, T6, T7, T8, T9, T10>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11> With<T5, T6, T7, T8, T9, T10, T11>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11, T12> With<T5, T6, T7, T8, T9, T10, T11, T12>() => default;

}

public readonly partial record struct TypeSet<T0, T1, T2, T3, T4, T5>
{

    public TypeSet<T0, T1, T2, T3, T4, T5, T6> With<T6>() => default;

    public TypeSet<T0, T1, T2, T3, T4, T5, T6, T7> With<T6, T7>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8> With<T6, T7, T8>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9> With<T6, T7, T8, T9>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10> With<T6, T7, T8, T9, T10>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11> With<T6, T7, T8, T9, T10, T11>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11, T12> With<T6, T7, T8, T9, T10, T11, T12>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11, T12, T13> With<T6, T7, T8, T9, T10, T11, T12, T13>() => default;

}

public readonly partial record struct TypeSet<T0, T1, T2, T3, T4, T5, T6>
{

    public TypeSet<T0, T1, T2, T3, T4, T5, T6, T7> With<T7>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8> With<T7, T8>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9> With<T7, T8, T9>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10> With<T7, T8, T9, T10>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11> With<T7, T8, T9, T10, T11>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11, T12> With<T7, T8, T9, T10, T11, T12>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11, T12, T13> With<T7, T8, T9, T10, T11, T12, T13>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11, T12, T13, T14> With<T7, T8, T9, T10, T11, T12, T13, T14>() => default;

}

public readonly partial record struct TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>
{

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8> With<T8>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9> With<T8, T9>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10> With<T8, T9, T10>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11> With<T8, T9, T10, T11>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11, T12> With<T8, T9, T10, T11, T12>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11, T12, T13> With<T8, T9, T10, T11, T12, T13>() => default;

    public TypeSet<TypeSet<T0, T1, T2, T3, T4, T5, T6, T7>, T8, T9, T10, T11, T12, T13, T14> With<T8, T9, T10, T11, T12, T13, T14>() => default;

}
